// <auto-generated />
namespace Zork_BR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nog_een_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nog_een_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201808231007410_nog_een_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
